name: Reusable_workflow_demo
on: 
  workflow_call:
jobs:
  reusable_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: This workflow can be Reusable
        run: echo "You are using Re Usable workFlow"
